<div class="loading-animation">
    <div class="loadingio-spinner-double-ring-u6qzmyfb91"><div class="ldio-td7342dymw">
    <div></div>
    <div></div>
    <div><div></div></div>
    <div><div></div></div>
    </div></div>
</div>
<style type="text/css">
@keyframes ldio-td7342dymw {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-td7342dymw div { box-sizing: border-box!important }
.ldio-td7342dymw > div {
  position: absolute;
  width: 93.6px;
  height: 93.6px;
  top: 11.7px;
  left: 11.7px;
  border-radius: 50%;
  border: 11.7px solid #000;
  border-color: #157759 transparent #157759 transparent;
  animation: ldio-td7342dymw 1s linear infinite;
}

.ldio-td7342dymw > div:nth-child(2), .ldio-td7342dymw > div:nth-child(4) {
  width: 67.86px;
  height: 67.86px;
  top: 24.57px;
  left: 24.57px;
  animation: ldio-td7342dymw 1s linear infinite reverse;
}
.ldio-td7342dymw > div:nth-child(2) {
  border-color: transparent #53ab8b transparent #53ab8b
}
.ldio-td7342dymw > div:nth-child(3) { border-color: transparent }
.ldio-td7342dymw > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-td7342dymw > div:nth-child(3) div:before, .ldio-td7342dymw > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 11.7px;
  height: 11.7px;
  top: -11.7px;
  left: 29.25px;
  background: #157759;
  border-radius: 50%;
  box-shadow: 0 81.89999999999999px 0 0 #157759;
}
.ldio-td7342dymw > div:nth-child(3) div:after {
  left: -11.7px;
  top: 29.25px;
  box-shadow: 81.89999999999999px 0 0 0 #157759;
}

.ldio-td7342dymw > div:nth-child(4) { border-color: transparent; }
.ldio-td7342dymw > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-td7342dymw > div:nth-child(4) div:before, .ldio-td7342dymw > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 11.7px;
  height: 11.7px;
  top: -11.7px;
  left: 16.38px;
  background: #53ab8b;
  border-radius: 50%;
  box-shadow: 0 56.16px 0 0 #53ab8b;
}
.ldio-td7342dymw > div:nth-child(4) div:after {
  left: -11.7px;
  top: 16.38px;
  box-shadow: 56.16px 0 0 0 #53ab8b;
}
.loadingio-spinner-double-ring-u6qzmyfb91 {
  width: 117px;
  height: 117px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-td7342dymw {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-td7342dymw div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>